dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=FirefoxHeadless
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js