dist: xenial
sudo: false

language: node_js
node_js:
  - "10"

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable

cache:
  directories:
     - ./node_modules

before_install:
  - export TZ=America/Bogota
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install
  - ./node_modules/protractor/bin/webdriver-manager update

script:
  - npm run test -- --no-watch --no-progress --browsers=FirefoxHeadless
  # End-to-end testing is pending...
  # - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js