import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from '@nativescript/angular';
import { Routes } from '@angular/router';

import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { NotebookComponent } from '@src/app/feature/notebook/notebook.component';
import { CalendarComponent } from '@src/app/feature/calendar/calendar.component';

export const routes: Routes = [
  { path: 'notebook', component: NotebookComponent },
  { path: 'calendar', component: CalendarComponent }
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
