import { NgModule, NO_ERRORS_SCHEMA, LOCALE_ID } from '@angular/core';
import { NativeScriptModule } from '@nativescript/angular';
import localeEs from "@angular/common/locales/es";
registerLocaleData(localeEs);

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { CoreModule } from '@src/app/core/core.module.tns';
import { FeatureModule } from '@src/app/feature/feature.module.tns';
import { SharedModule } from '@src/app/shared/shared.module.tns';
import { registerLocaleData } from '@angular/common';


// Uncomment and add to NgModule imports if you need to use two-way binding and/or HTTP wrapper
// import { NativeScriptFormsModule, NativeScriptHttpClientModule } from '@nativescript/angular';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
    FeatureModule,
    CoreModule,
    SharedModule
  ],
  providers: [
    { provide: LOCALE_ID, useValue: 'es-CO' }
  ],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
